/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agustia_employeewagesystem;

import com.mycompany.agustia_employeewagesystem.Class.EriEmployee;
import com.mycompany.agustia_employeewagesystem.Class.EriRegularEmployee;
import com.mycompany.agustia_employeewagesystem.Class.EriTemporaryEmployee;
import java.util.ArrayList;

/**
 *
 * @author erina
 */
public class FormDisplay extends javax.swing.JFrame {

    ArrayList<EriEmployee> employees;
    /**
     * Creates new form FormPlay
     */
    public FormDisplay(ArrayList<EriEmployee> employees) {
        initComponents();
        this.employees = employees;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radioButtonAll = new javax.swing.JRadioButton();
        radioButtonRegular = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radioButtonTemporary = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonGroup1.add(radioButtonAll);
        radioButtonAll.setText("All");
        radioButtonAll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonAllStateChanged(evt);
            }
        });
        radioButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAllActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonRegular);
        radioButtonRegular.setText("Regular");
        radioButtonRegular.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonRegularStateChanged(evt);
            }
        });
        radioButtonRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonRegularActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee Type");

        buttonGroup1.add(radioButtonTemporary);
        radioButtonTemporary.setText("Temporary");
        radioButtonTemporary.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonTemporaryStateChanged(evt);
            }
        });
        radioButtonTemporary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonTemporaryActionPerformed(evt);
            }
        });

        textAreaInfo.setColumns(20);
        textAreaInfo.setRows(5);
        jScrollPane1.setViewportView(textAreaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonTemporary, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonRegular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonTemporary)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonRegularActionPerformed

    private void radioButtonTemporaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonTemporaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonTemporaryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String print = "";
            for(EriEmployee emp : employees) {
                print = emp.displayEmployee() + "\n"
                        + emp.calculateBonus() + "\n"
                        + "===================================";
            }
            
            textAreaInfo.setText(print);
    }//GEN-LAST:event_formWindowOpened

    private void radioButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAllActionPerformed

    private void radioButtonAllStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonAllStateChanged
        // TODO add your handling code here:
        textAreaInfo.setText("");
                
        if(radioButtonAll.isSelected()) {
        String print = "";
            for(EriEmployee emp : employees) {
                print = emp.displayEmployee() + "\n"
                        + emp.calculateBonus() + "\n"
                        + "===================================";
            }
            
            textAreaInfo.setText(print);
        }
        
    }//GEN-LAST:event_radioButtonAllStateChanged

    private void radioButtonRegularStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonRegularStateChanged
        // TODO add your handling code here:
       textAreaInfo.setText("");
                
        if(radioButtonRegular.isSelected()) {
        String print = "";
            for(EriEmployee emp : employees) {
                if(emp instanceof EriRegularEmployee) {
                 print = emp.displayEmployee() + "\n"
                        + emp.calculateBonus() + "\n"
                        + "===================================";                   
                }
            }
            
            
            textAreaInfo.setText(print);
        }
        
    }//GEN-LAST:event_radioButtonRegularStateChanged

    private void radioButtonTemporaryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonTemporaryStateChanged
        // TODO add your handling code here:
        textAreaInfo.setText("");
                
        if(radioButtonRegular.isSelected()) {
        String print = "";
            for(EriEmployee emp : employees) {
                if(emp instanceof EriTemporaryEmployee) {
                 print = emp.displayEmployee() + "\n"
                        + emp.calculateBonus() + "\n"
                        + "===================================";                   
                }
            }
            
            
            textAreaInfo.setText(print);
        }
    }//GEN-LAST:event_radioButtonTemporaryStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioButtonAll;
    private javax.swing.JRadioButton radioButtonRegular;
    private javax.swing.JRadioButton radioButtonTemporary;
    private javax.swing.JTextArea textAreaInfo;
    // End of variables declaration//GEN-END:variables
}
