/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agustia_perpustakaan;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author erina
 */
public class RentFrame extends javax.swing.JFrame {

    /**
     * Creates new form RentFrame
     */
    
    Rent rent;
    
    public RentFrame() {
        
        initComponents();
        rent = new Rent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisMobil = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        kategoriBuku = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        comboBoxID = new javax.swing.JComboBox<>();
        radioButtonAdd = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        radiobuttonDosen = new javax.swing.JRadioButton();
        radiobuttonPendidik = new javax.swing.JRadioButton();
        radiobuttonMahasiswa = new javax.swing.JRadioButton();
        radiobuttonUmum = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        textFieldMerk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerSewa = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spinnerBack = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaInfo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        spinnerRencana = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        radiobuttonFiksi = new javax.swing.JRadioButton();
        radiobuttonNon = new javax.swing.JRadioButton();
        radiobuttonTeknologi = new javax.swing.JRadioButton();
        radiobuttonEkonomi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID :");

        buttonGroup1.add(radioButtonAdd);
        radioButtonAdd.setText("Add Data");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Modify Data");

        jLabel2.setText("Status Peminjam  :");

        jenisMobil.add(radiobuttonDosen);
        radiobuttonDosen.setText("Dosen");
        radiobuttonDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonDosenActionPerformed(evt);
            }
        });

        jenisMobil.add(radiobuttonPendidik);
        radiobuttonPendidik.setText("Tenaga Pendidik");

        jenisMobil.add(radiobuttonMahasiswa);
        radiobuttonMahasiswa.setText("Mahasiswa");
        radiobuttonMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonMahasiswaActionPerformed(evt);
            }
        });

        jenisMobil.add(radiobuttonUmum);
        radiobuttonUmum.setText("Umum");
        radiobuttonUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonUmumActionPerformed(evt);
            }
        });

        jLabel3.setText("Judul Buku  :");

        jLabel4.setText("Nama Peminjam :");

        jLabel5.setText("Kategori Buku :");

        jLabel6.setText("Harga Sewa :");

        jLabel7.setText("/ Hari");

        jLabel8.setText("Tgl Sewa :");

        spinnerSewa.setModel(new javax.swing.SpinnerDateModel());

        jLabel9.setText("Pengembalian :");

        spinnerBack.setModel(new javax.swing.SpinnerDateModel());

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textAreaInfo.setColumns(20);
        textAreaInfo.setRows(5);
        jScrollPane1.setViewportView(textAreaInfo);

        jLabel10.setText("Rencana P :");

        spinnerRencana.setModel(new javax.swing.SpinnerDateModel());

        jLabel11.setText("UTS - Perpustakaan by Agustia Eriani");

        jLabel12.setText("Bismillah");

        kategoriBuku.add(radiobuttonFiksi);
        radiobuttonFiksi.setText("Fiksi");

        kategoriBuku.add(radiobuttonNon);
        radiobuttonNon.setText("Non-Fiksi");

        kategoriBuku.add(radiobuttonTeknologi);
        radiobuttonTeknologi.setText("Teknologi");

        kategoriBuku.add(radiobuttonEkonomi);
        radiobuttonEkonomi.setText("Ekonomi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldMerk)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radiobuttonMahasiswa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radiobuttonDosen)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radiobuttonPendidik)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radiobuttonUmum))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radiobuttonFiksi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radiobuttonNon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radiobuttonTeknologi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radiobuttonEkonomi)))
                                        .addGap(0, 33, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spinnerRencana, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonAdd)
                    .addComponent(jRadioButton2)
                    .addComponent(comboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radiobuttonDosen)
                    .addComponent(radiobuttonPendidik)
                    .addComponent(radiobuttonMahasiswa)
                    .addComponent(radiobuttonUmum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radiobuttonFiksi)
                    .addComponent(radiobuttonNon)
                    .addComponent(radiobuttonTeknologi)
                    .addComponent(radiobuttonEkonomi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerRencana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinnerBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pesan = "";
        try {
            String jenis = "";
            if (radiobuttonPendidik.isSelected()) jenis = "Tenaga Pendidik";
            else if (radiobuttonDosen.isSelected()) jenis = "Dosen";
            else if (radiobuttonMahasiswa.isSelected()) jenis = "Mahasiswa";
            else if (radiobuttonUmum.isSelected()) jenis = "Umum";
            String nama   = textFieldNama.getText();
            String merk = textFieldMerk.getText();
            String plat = "";
            if (radiobuttonFiksi.isSelected()) plat = "Fiksi";
            else if (radiobuttonNon.isSelected()) plat = "Non-Fiksi";
            else if (radiobuttonTeknologi.isSelected()) plat = "Teknologi";
            else if (radiobuttonEkonomi.isSelected()) plat = "Ekonomi";
             
            //add data
            if (radioButtonAdd.isSelected()) {
                Rent rent1 = new Rent(0,nama,jenis,merk,plat,Double.parseDouble(textFieldHarga.getText()),(Date) spinnerSewa.getValue(),(Date) spinnerBack.getValue(),(Date) spinnerRencana.getValue());
                
                rent.addRent(rent1);
                
                comboBoxID.addItem(String.valueOf(rent1.getId()));
                
                pesan = "Data penyewa berhasil disimpan";
            }
            //modify data
            else{
                Rent rent1 = new Rent(0,nama,jenis,merk,plat,Double.parseDouble(textFieldHarga.getText()),(Date) spinnerSewa.getValue(),(Date) spinnerBack.getValue(),(Date) spinnerRencana.getValue());
                
                rent.updateRent(rent1, Integer.parseInt((String)comboBoxID.getSelectedItem()) );
                
                pesan = "Data Penyewa " + comboBoxID.getSelectedItem() + " berhasil diubah";
            }
            
        } catch(Exception e) {
            
        }
        
        JOptionPane.showMessageDialog(RentFrame.this, pesan);
        
        textAreaInfo.setText(rent.showDataRent());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radiobuttonMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttonMahasiswaActionPerformed

    private void radiobuttonDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttonDosenActionPerformed

    private void radiobuttonUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonUmumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttonUmumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jenisMobil;
    private javax.swing.ButtonGroup kategoriBuku;
    private javax.swing.JRadioButton radioButtonAdd;
    private javax.swing.JRadioButton radiobuttonDosen;
    private javax.swing.JRadioButton radiobuttonEkonomi;
    private javax.swing.JRadioButton radiobuttonFiksi;
    private javax.swing.JRadioButton radiobuttonMahasiswa;
    private javax.swing.JRadioButton radiobuttonNon;
    private javax.swing.JRadioButton radiobuttonPendidik;
    private javax.swing.JRadioButton radiobuttonTeknologi;
    private javax.swing.JRadioButton radiobuttonUmum;
    private javax.swing.JSpinner spinnerBack;
    private javax.swing.JSpinner spinnerRencana;
    private javax.swing.JSpinner spinnerSewa;
    private javax.swing.JTextArea textAreaInfo;
    private javax.swing.JTextField textFieldHarga;
    private javax.swing.JTextField textFieldMerk;
    private javax.swing.JTextField textFieldNama;
    // End of variables declaration//GEN-END:variables
}
