package latihanuas.annualtaxsystem;

import Kelas.EriTax;
import Kelas.EriBuldingTax;
import Kelas.EriVehicleTax;
import java.util.ArrayList;

/**
 *
 * @author acer
 */
public class FormDisplay extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDisplay.class.getName());
     ArrayList<EriTax> annualTaxs;
    /**
     * Creates new form FormDisplay
     */
    public FormDisplay( ArrayList<EriTax> annualTaxs) {
        initComponents();
        this.annualTaxs = annualTaxs;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTypeTax = new javax.swing.ButtonGroup();
        radioButtonBuilding = new javax.swing.JRadioButton();
        radioButtonVehicalTax = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaInfo = new javax.swing.JTextArea();
        radioButtonAll = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonGroupTypeTax.add(radioButtonBuilding);
        radioButtonBuilding.setText("Building Tax");
        radioButtonBuilding.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonBuildingStateChanged(evt);
            }
        });

        buttonGroupTypeTax.add(radioButtonVehicalTax);
        radioButtonVehicalTax.setText("Vehical Tax");
        radioButtonVehicalTax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonVehicalTaxStateChanged(evt);
            }
        });

        textAreaInfo.setColumns(20);
        textAreaInfo.setRows(5);
        jScrollPane1.setViewportView(textAreaInfo);

        buttonGroupTypeTax.add(radioButtonAll);
        radioButtonAll.setText("All");
        radioButtonAll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonAllStateChanged(evt);
            }
        });
        radioButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButtonAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(radioButtonVehicalTax)
                        .addGap(42, 42, 42)
                        .addComponent(radioButtonBuilding)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonAll)
                    .addComponent(radioButtonVehicalTax)
                    .addComponent(radioButtonBuilding))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String print = "";
        for(EriTax annualTax : annualTaxs){
            print +=  annualTax.toString() + "\n"
                    + "=============================\n";
        }
        textAreaInfo.setText(print);  
    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

            
    }//GEN-LAST:event_formWindowStateChanged

    private void radioButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAllActionPerformed

    private void radioButtonVehicalTaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonVehicalTaxStateChanged
        if(radioButtonVehicalTax.isSelected()){
            textAreaInfo.setText("");
            String print = "";
            
            for(EriTax annualTax : annualTaxs){
                if(annualTax instanceof EriVehicleTax){
                    print +=  annualTax.toString() + "\n"
                    + "=============================\n";
                }
               
        }
            textAreaInfo.setText(print);
        }
    }//GEN-LAST:event_radioButtonVehicalTaxStateChanged

    private void radioButtonAllStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonAllStateChanged
        textAreaInfo.setText("");
        
        if(radioButtonAll.isSelected()){
            String print = "";
            for(EriTax annualTax : annualTaxs){
            print +=  annualTax.toString() + "\n"
                    + "=============================\n";
        }
             textAreaInfo.setText(print);
        }
    }//GEN-LAST:event_radioButtonAllStateChanged

    private void radioButtonBuildingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonBuildingStateChanged
        textAreaInfo.setText("");
        
        if(radioButtonBuilding.isSelected()){
            
            String print = "";
            
            for(EriTax annualTax : annualTaxs){
                if(annualTax instanceof EriBuldingTax){
                    print +=  annualTax.toString() + "\n"
                        + "=============================\n";
                }
                
        }
            textAreaInfo.setText(print);
        }
    }//GEN-LAST:event_radioButtonBuildingStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTypeTax;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioButtonAll;
    private javax.swing.JRadioButton radioButtonBuilding;
    private javax.swing.JRadioButton radioButtonVehicalTax;
    private javax.swing.JTextArea textAreaInfo;
    // End of variables declaration//GEN-END:variables
}
