/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agustia_publishersistem;

import com.mycompany.agustia_publishersistem.Class.Article;
import com.mycompany.agustia_publishersistem.Class.Magazine;
import com.mycompany.agustia_publishersistem.Class.Publisher;
import java.util.ArrayList;

/**
 *
 * @author erina
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    
    public ArrayList<Publisher> publishers = new ArrayList<>();
    public ArrayList<Magazine> magazines = new ArrayList<>();
    public ArrayList<Article> articles = new ArrayList<>();
    
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdd = new javax.swing.JMenu();
        menuItemAddPublisher = new javax.swing.JMenuItem();
        menuItemAddMagazine = new javax.swing.JMenuItem();
        menuItemAddArticle = new javax.swing.JMenuItem();
        display = new javax.swing.JMenu();
        menuItemViewArticles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Use the menu above to get started");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("PUBLISHER INFORMATION SYSTEM");

        menuAdd.setText("Menu Add");

        menuItemAddPublisher.setText("Add Publisher");
        menuItemAddPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddPublisherActionPerformed(evt);
            }
        });
        menuAdd.add(menuItemAddPublisher);

        menuItemAddMagazine.setText("Add Magazine");
        menuItemAddMagazine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddMagazineActionPerformed(evt);
            }
        });
        menuAdd.add(menuItemAddMagazine);

        menuItemAddArticle.setText("Add Article");
        menuItemAddArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddArticleActionPerformed(evt);
            }
        });
        menuAdd.add(menuItemAddArticle);

        jMenuBar1.add(menuAdd);

        display.setText("Display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        menuItemViewArticles.setText("View Articles");
        menuItemViewArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemViewArticlesActionPerformed(evt);
            }
        });
        display.add(menuItemViewArticles);

        jMenuBar1.add(display);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddPublisherActionPerformed
        // TODO add your handling code here:
        FormPublisher formpublisher = new FormPublisher(publishers);
        formpublisher.setVisible(true);
    }//GEN-LAST:event_menuItemAddPublisherActionPerformed

    private void menuItemAddMagazineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddMagazineActionPerformed
        // TODO add your handling code here:
        FormMagazine formMagazine = new FormMagazine(publishers,magazines);
        formMagazine.setVisible(true);
        
    }//GEN-LAST:event_menuItemAddMagazineActionPerformed

    private void menuItemAddArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddArticleActionPerformed
        // TODO add your handling code here:
        FormArticle formArticle = new FormArticle(magazines);
        formArticle.setVisible(true);
    }//GEN-LAST:event_menuItemAddArticleActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void menuItemViewArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemViewArticlesActionPerformed
        // TODO add your handling code here:
        FormViewArticles formViewArticles = new FormViewArticles(publishers, magazines, articles);
        formViewArticles.setVisible(true);
    }//GEN-LAST:event_menuItemViewArticlesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdd;
    private javax.swing.JMenuItem menuItemAddArticle;
    private javax.swing.JMenuItem menuItemAddMagazine;
    private javax.swing.JMenuItem menuItemAddPublisher;
    private javax.swing.JMenuItem menuItemViewArticles;
    // End of variables declaration//GEN-END:variables
}
