/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kalkulatorpecahan_agustia;

import javax.swing.JOptionPane;

/**
 *
 * @author erina
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pecahan1TF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pecahan1TF2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pecahan2TF1 = new javax.swing.JTextField();
        pecahan2TF2 = new javax.swing.JTextField();
        tambahBTN = new javax.swing.JButton();
        kaliBTN = new javax.swing.JButton();
        bagiBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jawabanTA = new javax.swing.JTextField();
        kurangBTN = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pecahan1TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecahan1TF1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bilangan 1 :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Kalkulator Pecahan Agustia Eriani");

        jLabel3.setText("/");

        pecahan1TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecahan1TF2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bilangan 2 :");

        jLabel5.setText("/");

        pecahan2TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecahan2TF1ActionPerformed(evt);
            }
        });

        pecahan2TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecahan2TF2ActionPerformed(evt);
            }
        });

        tambahBTN.setText("+");
        tambahBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTNActionPerformed(evt);
            }
        });

        kaliBTN.setText("x");
        kaliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliBTNActionPerformed(evt);
            }
        });

        bagiBTN.setText(":");
        bagiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiBTNActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Result :");

        jawabanTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jawabanTAActionPerformed(evt);
            }
        });

        kurangBTN.setText("-");
        kurangBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangBTNActionPerformed(evt);
            }
        });

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pecahan2TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(pecahan1TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pecahan1TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pecahan2TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tambahBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kurangBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kaliBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bagiBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addComponent(jawabanTA, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pecahan1TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(pecahan1TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pecahan2TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pecahan2TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBTN)
                    .addComponent(kaliBTN)
                    .addComponent(bagiBTN)
                    .addComponent(kurangBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jawabanTA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void pecahan1TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecahan1TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pecahan1TF1ActionPerformed

    private void pecahan1TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecahan1TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pecahan1TF2ActionPerformed

    private void pecahan2TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecahan2TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pecahan2TF1ActionPerformed

    private void pecahan2TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecahan2TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pecahan2TF2ActionPerformed

    private void tambahBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTNActionPerformed
        // TODO add your handling code here:
        try {
            int P1 = Integer.parseInt(pecahan1TF1.getText());
            int PB1 = Integer.parseInt(pecahan1TF2.getText());
            int P2 = Integer.parseInt(pecahan2TF1.getText());
            int PB2 = Integer.parseInt(pecahan2TF2.getText());
            Calculator p1 = new Calculator(P1,PB1);
            Calculator p2 = new Calculator(P2,PB2);
        
            Calculator hasil = p1.tambah(p2);
    
            // Tampilkan ke label atau text field hasil
            jawabanTA.setText(hasil.toString());
            jawabanTA.setEditable(false);
            jawabanTA.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30));            
            // jika berhasil dialog ini 
            JOptionPane.showMessageDialog(this, "Berhasil menghitung :)", "Done", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            // jika gagal dialog ini
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahBTNActionPerformed

    private void kaliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliBTNActionPerformed
        // TODO add your handling code here:
        try {
            int P1 = Integer.parseInt(pecahan1TF1.getText());
            int PB1 = Integer.parseInt(pecahan1TF2.getText());
            int P2 = Integer.parseInt(pecahan2TF1.getText());
            int PB2 = Integer.parseInt(pecahan2TF2.getText());
            Calculator p1 = new Calculator(P1,PB1);
            Calculator p2 = new Calculator(P2,PB2);
        
            Calculator hasil = p1.kali(p2);
            
            jawabanTA.setText(hasil.toString());
            jawabanTA.setEditable(false);
            jawabanTA.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30)); 
            // jika berhasil dialog ini 
            JOptionPane.showMessageDialog(this, "Berhasil menghitung :)", "Done", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            // jika gagal dialog ini
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kaliBTNActionPerformed

    private void bagiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiBTNActionPerformed
        // TODO add your handling code here:
        try {
            int P1 = Integer.parseInt(pecahan1TF1.getText());
            int PB1 = Integer.parseInt(pecahan1TF2.getText());
            int P2 = Integer.parseInt(pecahan2TF1.getText());
            int PB2 = Integer.parseInt(pecahan2TF2.getText());
            Calculator p1 = new Calculator(P1,PB1);
            Calculator p2 = new Calculator(P2,PB2);
        
            Calculator hasil = p1.bagi(p2);
            
            jawabanTA.setText(hasil.toString());
            jawabanTA.setEditable(false);
            jawabanTA.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30)); 
            // jika berhasil dialog ini 
            JOptionPane.showMessageDialog(this, "Berhasil menghitung :)", "Done", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            // jika gagal dialog ini
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
                  
    }//GEN-LAST:event_bagiBTNActionPerformed

    private void jawabanTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jawabanTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jawabanTAActionPerformed

    private void kurangBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangBTNActionPerformed
        // TODO add your handling code here:
        try {
            int P1 = Integer.parseInt(pecahan1TF1.getText());
            int PB1 = Integer.parseInt(pecahan1TF2.getText());
            int P2 = Integer.parseInt(pecahan2TF1.getText());
            int PB2 = Integer.parseInt(pecahan2TF2.getText());
            Calculator p1 = new Calculator(P1,PB1);
            Calculator p2 = new Calculator(P2,PB2);
        
            Calculator hasil = p1.kurang(p2);
            
            jawabanTA.setText(hasil.toString());
            jawabanTA.setEditable(false);
            jawabanTA.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30)); 
            // jika berhasil dialog ini 
            JOptionPane.showMessageDialog(this, "Berhasil menghitung :)", "Done", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            // jika gagal dialog ini
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kurangBTNActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        pecahan1TF1.setText("");
        pecahan1TF2.setText("");
        pecahan2TF1.setText("");
        pecahan2TF2.setText("");
        jawabanTA.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagiBTN;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jawabanTA;
    private javax.swing.JButton kaliBTN;
    private javax.swing.JButton kurangBTN;
    private javax.swing.JTextField pecahan1TF1;
    private javax.swing.JTextField pecahan1TF2;
    private javax.swing.JTextField pecahan2TF1;
    private javax.swing.JTextField pecahan2TF2;
    private javax.swing.JButton tambahBTN;
    // End of variables declaration//GEN-END:variables
}
